import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { ThemeProvider } from "@/components/theme-provider";
import { siteConfig } from "../../config/site";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-full flex flex-col min-h-screen text-pretty text-sm md:text-lg">
            <Header items={siteConfig.mainNav} />
            <div className="flex flex-1 md:container md:mx-auto">
              {children}
            </div>
            {/* <footer>Footer</footer> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
